export const TEXTS = [
  "¿Respondo al perfil del emprendedor? Para responder a la pregunta creo que es necesario apoyarse en mis puntos fuertes y los débiles. Haciendo un análisis DAFO de mi perfil profesional y personal, creo que entre mis fortalezas se encuentran la empatía, la creatividad, soy también buena comunicadora y me considero muy trabajadora. Sin embargo, entre mis debilidades se incluyen la capacidad de liderazgo, la tolerancia a la frustración o el miedo al riesgo. Mis amenazas son mis propios sentimientos de inseguridad y de síndrome de impostor, pero mi oportunidad es la de realizar un proyecto con alma y en el que realmente llevo creyendo varios años. ",
  "A continuación, hago un repaso de mis datos personales y profesionales: ",
  "Soy Marisol Peña (en el entorno laboral), soy almeriense y durante más de seis años he desempeñado mi carrera profesional en Madrid al lado, principalmente de empresas del sector tecnológico y siempre trabajando por cuenta ajena. Estudié Periodismo en la Universidad de Málaga y varios másteres relacionados con el sector audiovisual, lo que me permitió trabajar como comunicadora y organizadora de eventos. Tras la pandemia, y tras perder mi empleo, decidí reinventarme y realicé el Bootcamp de desarrollo web de Adalab, una organización orientada a la inclusión de mujeres en el mundo de la tecnología. Desde entonces, hace más de dos años, llevo trabajando como programadora web en el área de frontend, primero en una consultora tecnológica y, actualmente en una empresa de producto del sector bancario.",
  "¿Por qué crear una empresa? Son varios los motivos. Conforme fui creciendo a nivel profesional empecé a ver la gran brecha digital que existía en Almería. Ya no solo para mis oportunidades laborales si decidía volver a mi lugar natal, sino también para amigos y familiares que habían decidido quedarse y cuyas aspiraciones se iban cerrando poco a poco al no dedicarse al sector primario. Además, desde la pandemia trabajo en remoto, así que mis oportunidades laborales se reducen en general a las políticas de teletrabajo que tenga la empresa de turno. ",
  "Entonces, empecé a tomar más conciencia de la necesidad de impulsar el desarrollo económico almeriense. Me animé, sobre todo, cuando vi que ya había otras empresas que estaban impulsando la innovación y la tecnología más allá de nuestras fronteras, como puede ser la empresa de Coderty, Digital 55 o Twenix.",
  "Además, tras más de seis años trabajando en empresas grandes (en su mayoría), comprendí que mi corazón está en los lugares pequeños, donde se trabaja mano a mano y por un objetivo común. Mi motivación aumenta cuando creo 100% en el proyecto.",
  "Por último, Blue Tech me permite converger mis dos grandes pasiones, la comunicación y la programación. Trabajando por cuenta ajena he tenido que elegir entre estas áreas, pero creando mi propio trabajo puedo aunar las dos, sacando el máximo provecho.",
  "Y, ¿pretendo hacer esto yo sola? Para nada, como se suele decir, si quieres llegar rápido ve sola, pero si quieres llegar lejos ve acompañada. Blue Tech estará también conformada por mi fiel escudero Adrián Alonso, programador Full Stack. Cuenta con más de diez años de experiencia en el sector tecnológico desarrollando diversas tecnologías. Además, es amante de la formación y ha participado en diversas charlas y también como mentor de causas benéficas. Su gran experiencia aportará valor a la empresa, pero también al cliente.",
];
