export const TEXTS = [
  "En un primer momento, Blue Tech se compondrá exclusivamente de los socios de la empresa, es decir, solo dos personas. La incertidumbre por la vida viable de la empresa nos hace tomar esta decisión aunque sabemos que un apoyo extra o otro tipo de perfil nos ayudaría mucho en nuestro camino hacia el éxito. Así nuestro pequeño equipo se repartirá el número de tareas a realizar en este momento tan trascendental para Blue Tech.",
  "Las principales funciones a realizar en Blue Tech las podemos dividir en dos apartados: desarrollo web y marketing. En mi caso, me encargaré de la comunicación de la empresa a través de las redes sociales, la publicidad, también nuestra página web... Además de ello, trabajaré en la parte del desarrollo frond de nuestos proyectos. Por la parte de mi socio, se encargará de la parte de desarrollo backend de los proyectos, así como las tareas relacionadas con devops. Además, será el responsable de la gestión de proyectos y la comunicación con el cliente. Hemos dividido así nuestras responsabilidades atendiendo a nuestros perfiles profesionales previos.",
  "Respecto a mi perfil profesional, soy Graduada en Periodismo con máster en Comunicación y con más de tres años de experiencia desarrollando este rol siempre en empresas relacionadas con el mundo tech. Además, desde hace cuatro años, mi rol se especializó en el desarrollo web gracias a la realización del mundo de Adalab. Tras esto, he trabajado como desarrolladora frontend durante casi tres años, así continúo formándome en este campo con la realización de la FP Desarrollo de Aplicaciones Multimedia.",
  "Adrián Alonso, mi socio, es titulado en Ingeniería Informática y cuenta con más de 10 años de experiencia en esta área, desarrollando tareas como desarrollador Backend, Team Lead, así como Devops. Complementó su formación con un máster en Gestión de Proyectos y ha desempeñado esta tarea en varios proyectos finalizados con éxito. Además, cuenta ya con experiencia en la atención al cliente pues ha desarrollado proyectos como colaborar externo en diferentes proyectos de startup. Por lo que lo convierte en un perfil idóneo para gestionar las relaciones de Blue Tech con los clientes. De esta forma, el organigrama de la empresa quedaría así: ",
];

export const NEW_TEXTS = [
  "Seguimos con el aparatado de proceso de selección. Este se inicia con una autoevaluación de Blue Tech, donde se identifican las habilidades, fortalezas y debilidades del equipo. Este análisis permite la definición clara de roles y responsabilidades, centrándose en las especialidades de cada miembro del equipo. Se busca una complementariedad equilibrada para garantizar una colaboración eficiente y abordar integralmente las necesidades de Blue Tech. Se realizarán entrevistas bidireccionales para discutir metas, expectativas y la visión se tiene para Blue Tech. Además, se llevarán a cabo pruebas prácticas colaborativas, simulando la gestión de proyectos o la creación de estrategias de comunicación, para evaluar la sinergia en el trabajo conjunto. Este enfoque no solo se centra en habilidades individuales, sino también en la capacidad de colaborar de manera efectiva. La evaluación de la visión empresarial será un paso crucial, donde se revisarán las metas a largo plazo y la dirección estratégica de Blue Tech. La coincidencia en estos aspectos es fundamental para asegurar una colaboración armoniosa y un compromiso compartido con el éxito del negocio.",
  "Con referencia al coste de cada puesto de trabajo. Se realizará una distribución equitativa de los beneficios y reinversión en el crecimiento del negocio. Esta estrategia se seguirá al menos hasta que Blue Tech pueda ir creciendo y contratemos a nuevo personal. En este caso nos informaríamos de la contrtación de trabajadores en los organismos oficiales y estableceríamos un salario justo acorde a los conocimientos y el valor aportado.",
  "Por último, como plan de gestión del equipo, estableceríamos canales de comunicación abiertos y directos entre los trabajadores (en un primer caso entre los fundadores). Me gusta mucho el uso de programas de chats en tiempo real como Slack o Teams que facilita mucho la comunicación si no estás en un entorno físico. Por supuesto, estos canales se complementarán con una comunicación efectiva en persona. Respecto a la motivación de los empleados, creemos en los logros y la visión compartida del éxito en Blue Tech, intentaremos celebrar nuestras victorias en los proyectos, pero tambián aunar nuestros esfuerzos en los problemas. Y, aquí tiene mucho que ver la formación y el crecimiento de nuestro equipo, sin su confianza no podría existir Blue Tech, así que una forma indirecta de motivación también es la formación continua, ya sea a través de cursos o incluso, cualquier formación reglada. En cuanto a la resolución de conflictos, nos gustaría también mantener un canal de comunicación abierto para poder mediar si se produce esta casuística. Creemos en el diálogo abierto y en el enfoque de soluciones conjuntas. Por último, confiamos en un liderazgo participativo y en el equipo para la toma de decisiones, así podemos sacar provecho de la experiencia y los conocimientos individuales.",
];
