export const TEXTS = [
  "En Blue Tech optamos por externalizar el servicio de prevención a través de un servicio de prevención ajeno. Sabemos que el módulo de la FP Formación y Orientación Laboral nos da las bases para conocer esta materia y su importancia, pero creo que no la suficiente para llevar este tema nosotros solos. Por lo que, esta elección se basa en la especialización y conocimiento técnico que ofrecen los profesionales externos en materia de prevención de riesgos laborales. Al contratar un servicio de prevención ajeno, garantizamos la independencia, objetividad y experiencia necesarias para identificar, evaluar y controlar los riesgos laborales de manera eficiente en Blue Tech.",
  "Esta modalidad permite a Blue Tech centrarse en su especialidad principal, la transformación digital para PYMES, mientras nos aseguramos que la gestión de la prevención de riesgos laborales cumple con los requisitos normativos y se aborda de manera efectiva. La externalización proporciona flexibilidad y acceso a recursos especializados sin incrementar la carga administrativa interna, optimizando así la eficacia en la prevención de riesgos laborales.",
];

export const RISKS = [
  "La realidad del sector tecnológico es un largo periodo de tiempo sentado en una silla y acoplado a una pantalla que contiene toda la sabiduría de tu proyecto. Y, lamentablemente, Blue Tech no es una excepción en este paradigma, y nuestras principales actividades se llevan a cabo en entornos, por así decirlo de oficina. Por este motivo, identificamos el riesgo ergonómico / de lesiones físicas como una preocupación clave. Esto es, por ejemplo, dolores de espalda por pasar un tiempo excesivo sentado, perdida de visión, dolor en los hombros, mala circulación y un largo etcétera. Para mitigar este riesgo, implementaremos directamente medidas ergonómicas en los espacios de trabajo, incluyendo mobiliario ajustable como mesas elevables, reposapies, pelotas de pilates que ayudan a mantener la espalda recta, máquinas para poder andar mientras trabajas, disposición adecuada de equipos, la promoción de pausas activas y ayuda para sesiones de fisio.",
  "Además, realizaremos evaluaciones ergonómicas periódicas para identificar posibles problemas y proporcionaremos formación a los empleados sobre prácticas ergonómicas saludables. La inversión en ergonomía no solo promueve la salud y el bienestar de nuestro equipo, sino que también contribuye a la productividad y eficiencia a largo plazo. Pues, al final esto se traduce en trabajadores más contentos, con mejor estado físico y mental y con ganas de aportar el máximo en los proyectos. ",
];
